### ISSUE TITLE
Host page problem

### ISSUE THREAD

**Issue by wufatmio** [ZionDevelopers/playx#103]
The new host page will automatically initialize JWPlayer but that will broke flash and googledrive provider.

**Comment by juliocoliveira** [comment]
I'll need more then that.
Like a video example with full URL on google drive.

**Comment by juliocoliveira** [comment]
Well i see the problem, But i cannot give you a solution for it, Since the Flash provider injects HTML to the body of the page so doesn't matter whatever i have put on the PlayX host it will be replaced by PlayX Flash provider.

Your addon always worked, And even after i changed the PlayX host, And it stopped just a few days ago.
I think i figured out what the problem is.
When you play
 https://video.google.com/get_player?docid=0B0JMGMGgxp9WMEdWb1hyQUhlOWs&=docs&partnerid=30&cc_load_policy=1&controls=0&showsearch=0&showinfo=0&version=3&autoplay=1&rel=0&enablejsapi=1

But https://video.google.com/crossdomain.xml is stopping from the flash being played, Since as you can see <allow-access-from domain="s.ytimg.com" />
<allow-access-from domain="*.youtube.com" />
It only allow access from youtube.com domain.

So there is nothing i can do to fix that.

You will need change your Provider to another workaround, Like using Handler iFrame and URL https://drive.google.com/file/d/FILE_ID_HERE/preview
like https://drive.google.com/file/d/0B0JMGMGgxp9WMEdWb1hyQUhlOWs/preview and then play it by javascript since any ?autoplay=1 don't seams to work.

Best luck to you.

**Comment by wufatmio** [comment]
You just need add a check in your init.js, if video url is null then do not initialize JWPlayer.

**Comment by juliocoliveira** [comment]
Done, See if works now.

**Comment by wufatmio** [comment]
Its work now, thanks!
