### ISSUE TITLE
Error Appears When Spawning (DarkRP)

### ISSUE THREAD

**Issue by Nacoles** [ZionDevelopers/playx#107]
There is no Lua error to show (I don't know why) but in DarkRP when I try to spawn in the theater addon by f4 Theater Manager job entity, I get this on my screen: http://i.imgur.com/ZLcfrXI.jpg

I just want to create an entity that can be used by other players with the ULX and Ulib script.

I am running PlayX off of the Steam Workshop gmad file.

**Comment by Nacoles** [comment]
Tell me if I need to change the file type (with a download link) or if I need to edit the files so that this does not happen again.

**Comment by juliocoliveira** [comment]
Probably because you don't have the model on the server / local.
The most projectors / tvs  is from CSS.
Make sure that you have that model installed.

If didn't show any lua errors, it's because there no any.

Júlio César de Oliveira
Web Developer
----------------------------------------------------------
Website: http://www.juliocesar.me
E-mail: talk*@juliocesar.me* <talk@juliocesar.me>
----------------------------------------------------------
Residential phone: +55 (14) 3621-6157
Mobile: +55 (14) 9 9799-6232 <+5514997996232>
<https://about.me/juliocesaroliveira?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=edit_panel&utm_content=thumb>
Júlio Oliveira
about.me/juliocesaroliveira
<https://about.me/juliocesaroliveira?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=edit_panel&utm_content=thumb>

**Comment by Nacoles** [comment]
I can spawn it in from the Q menu and set its models of which I already have...

...but it comes up as an error on this menu: http://i.imgur.com/e5IV9VT.png

Hopefully you can have a better understand the situation now.

**Comment by juliocoliveira** [comment]
That menu, was not developed by us.
Talk to the developer of that DarkRP extension.
