### ISSUE TITLE
Livestreams like Ustream.tv don't work

### ISSUE THREAD

**Issue by CatIsHappy** [ZionDevelopers/playx#78]
It doesnt recognize the link. I do Non-browseable web page but it gets cut off by part of the page so I only see partial screen.

**Comment by juliocoliveira** [comment]
We cannot give support to all the providers in the world, Because there is too many, and not all providers give support for API.

What you can do to make it easier is get a embed code, And if is a iframe you can get the URL and open on the PlayX as a non-browse-able page.

OR if is a Flash open as Flash Provider on PlayX.

This is NOT a Issue, We cannot make PlayX work with all the media providers in the world, But you can try make it work for the ones you want, just need be smart.
